version: '3'

services:

  # Angular App
  angular-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run angular-app:dev:docker
    ports:
      - 4203:4200
    depends_on:
      - backend-api
    env_file: .env

  # Express API
  backend-api:
    depends_on:
      - mysqldb
    env_file: .env
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend-api:dev:docker
    ports:
      - $NODE_DOCKER_PORT:$NODE_LOCAL_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:8.0.17
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_DOCKER_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  mono-node-modules: null