version: '3'

services:
  # Angular App
  angular-app:
    container_name: angular-app
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run angular-app:dev:docker
    ports:
      - $ANGULAR_DOCKER_PORT:$ANGULAR_LOCAL_PORT
    depends_on:
      - backend-api
    env_file: .env

  # Express API
  backend-api:
    container_name: backend-api
    depends_on:
      - mysqldb
    env_file: .env
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend-api:dev:docker
    ports:
      - $NODE_DOCKER_PORT:$NODE_LOCAL_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

  # MySQL Database
  mysqldb:
    container_name: mysql
    image: mysql:8.0.17
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_DOCKER_PORT:$DB_PORT
    volumes:
      - mysql-db:/var/lib/mysql
      # TODO: fix healthcheck to make sure mysql loads fully until backend api loads
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-db:
  mono-node-modules: null