version: '3'

services:

  # Angular App
  angular-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run angular-app:dev:docker
    ports:
      - 4203:4200
  
  # Express API
  api-1:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend-api:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port

volumes:
  mono-node-modules: null